import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: "class",
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "stitch-background": "#f8f9fa",
        "on-error-container": "#6e0a12",
        "on-surface-variant": "#5a6062",
        "tertiary-container": "#d4c8f9",
        "surface-container-low": "#f1f4f5",
        "on-secondary": "#f8f8ff",
        "surface-variant": "#dee3e6",
        "inverse-surface": "#0c0f10",
        "stitch-primary": "#575f75",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed-variant": "#535b71",
        "surface-container-high": "#e5e9eb",
        "secondary-container": "#d7e3f8",
        "error": "#a83836",
        "tertiary-fixed": "#d4c8f9",
        "on-tertiary-fixed": "#352c53",
        "on-secondary-fixed": "#354050",
        "inverse-primary": "#dae2fd",
        "surface-tint": "#575f75",
        "tertiary-fixed-dim": "#c6baea",
        "primary-dim": "#4b5369",
        "error-dim": "#67040d",
        "outline-variant": "#adb3b5",
        "on-tertiary-fixed-variant": "#524972",
        "surface-container": "#ebeef0",
        "secondary-fixed": "#d7e3f8",
        "primary-fixed": "#dae2fd",
        "tertiary-dim": "#564d76",
        "primary-fixed-dim": "#ccd4ee",
        "secondary-fixed-dim": "#c9d5e9",
        "on-tertiary": "#fdf7ff",
        "on-secondary-fixed-variant": "#515c6d",
        "on-background": "#2d3335",
        "surface-dim": "#d5dbdd",
        "error-container": "#fa746f",
        "primary-container": "#dae2fd",
        "inverse-on-surface": "#9b9d9e",
        "tertiary": "#625983",
        "outline": "#767c7e",
        "on-error": "#fff7f6",
        "on-surface": "#2d3335",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dee3e6",
        "surface": "#f8f9fa",
        "on-tertiary-container": "#494068",
        "stitch-secondary": "#546071",
        "on-primary": "#f9f8ff",
        "on-primary-fixed": "#373f54",
        "on-primary-container": "#4a5167",
        "on-secondary-container": "#475263",
        "secondary-dim": "#485465",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
